### ISSUE TITLE
IMPORTANT: repository name

### ISSUE THREAD

**Issue by randaz81** [robotology/yarp-devices-forcetorque#33]
We are reorganizing all the robotology repositories related to yarp plugins.
They should use the standard identification: **yarp-devices-***
Could you rename this repository to **yarp-devices-forcetorque**?
Thank you!

**Comment by traversaro** [comment]
I think there should not be a lot of problems, we just need to rename as well the repo in robotology-superbuild . What do you think @RiccardoGrieco ?

**Comment by RiccardoGrieco** [comment]
This issue can be closed.

**Comment by traversaro** [comment]
Thanks!
